### ISSUE TITLE
Displaying Tweets

### ISSUE THREAD

**Issue by anshuman73** [fossasia/fossasia-loklak-webtweets#14]
The white space background doesn't cover the tweets sometimes.
![screenshot(https://cloud.githubusercontent.com/assets/12889549/12216027/99516fa8-b6fa-11e5-9f36-4235aa68ee97.png)

Reference to commit #13

**Comment by mariobehling** [comment]
Ok, got it. As a matter of fact, we can just make a white background site. The goal of this project is not to have a website with a top designed page. The goal is to get the functionality, that can be used in many different websites independently of the design.

**Comment by yasoob** [comment]
I am working on this issue. I have solved it. Just going to make a pull request in a min :).
