### ISSUE TITLE
Tweets do not loop

### ISSUE THREAD

**Issue by codethejason** [fossasia/fossasia-loklak-webtweets#16]
After the the tweets in the JSON are gone through, the app does not loop back to the first tweet.  

![tweet doesn't loop](http://puu.sh/msySH/3fbb8a42f8.png)

**Comment by anshuman73** [comment]
HI, has this issue been solved ?

@mariobehling Could you close this issue if this is its' solved ?

**Comment by mariobehling** [comment]
If this has been resolved, please document it in the Readme.md. Is it possible to control how many tweets are shown before the loop starts again? E.g. it would be nice to control if I show the last 8 tweets or the last 12 for example.

**Comment by codethejason** [comment]
@mariobehling That's what the data-count is for, or are you thinking of something different?

**Comment by mariobehling** [comment]
Ok, good job. Saw it was documented. Thanks! Would be great to have options like show tweets of specific hashtag(s), user(s), in a specific time frame. Please also check out this issue for the FOSSASIA.org website. It would be fantastic, if we could implement this now on the FOSSASIA main site. https://github.com/fossasia/fossasia.org/issues/5

**Comment by codethejason** [comment]
@mariobehling I can add the fact that one can add any hashtag or user directly to the search query to the documentation.

**Comment by mariobehling** [comment]
Yes, please. Also add info what syntax should be used, e.g. restriction like from:user or so. And give examples in the documentation. Cheers.
