### ISSUE TITLE
Line break within words

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-loklak-webtweets#18]
Currently line breaks in words happen in many tweets.

![screenshot from 2016-01-12 09 51 03](https://cloud.githubusercontent.com/assets/1583873/12258869/261d938a-b912-11e5-8224-326b5e49da48.png)

**Comment by ghost** [comment]
Rectified the above issue .. Plz check out pull request #19 @mariobehling 
I have retained the breaking property for very long hyperlinks inorder to keep the proportion of tweet box same

**Comment by mariobehling** [comment]
Good job.
