### ISSUE TITLE
interval() doesn't wait for the tweets to be gathered

### ISSUE THREAD

**Issue by YagoGG** [fossasia/fossasia-loklak-webtweets#23]
# Description

If loklak API is taking longer than usual to answer, the `interval()` function will begin sliding through the tweets, but because there are aren't any, the application will display errors every 6.6 seconds until loklak responds.
# Steps to reproduce
1. Open loklak webtweets
2. In Chrome DevTools, go to the tab **Network**. There, click in _No throttling_ and choose a REALLY slow connection (GPRS @ 50kb/s worked for me)
3. Reload the page
4. The different elements in the page should begin loading, and a few seconds after the query to loklak has been made, the console will display the following error:

> Uncaught ReferenceError: stuff is not defined (tweets.js:25)
# Additional information

Having such a slow connection is quite improbable, fine, but I discovered this when loklak API was working a bit slow, something that could perfectly happen under normal circumstances.
# Screenshot

![Chrome DevTools](https://cloud.githubusercontent.com/assets/7356565/12374427/3f344134-bc9b-11e5-9f2b-ff8328e64dfe.png)

**Comment by YagoGG** [comment]
I think I know how this issue could be solved. May I have it assigned?

**Comment by jigyasa-grover** [comment]
@YagoGG Go ahead :)

**Comment by YagoGG** [comment]
Thanks, @jig08!
