### ISSUE TITLE
Different working schema

### ISSUE THREAD

**Issue by anshuman73** [fossasia/fossasia-loklak-webtweets#3]
Well, to improve the features provided by this site (ability to call different keywords, time, etc) I am in the process of building the support based on the library provided by Yago. (https://github.com/YagoGG/loklak-fetcher-client) But I see an angular file has been merged already. Should I work with that now or should I continue working with mine ? The current result doesn't seem to work at http://fossasia.github.io/fossasia-loklak-webtweets/ for some reason anyway.

**Comment by mariobehling** [comment]
Just do whatever is easier for you to get a working solution. Cheers.

**Comment by mariobehling** [comment]
I do not see that it is working. Any idea?

**Comment by anshuman73** [comment]
Hmm. Yes, see the console. It's facing the same problem I was before I opted to use Yago's script. Angular makes an ajax request. And an ajax request is restricted to same domain.

**Comment by DengYiping** [comment]
Hello! That is a server site problem, and it is a bug in Chrome. @anshuman73 The code is actually working.

**Comment by anshuman73** [comment]
Ahh. It works with other browsers ?

**Comment by mariobehling** [comment]
No, since you can't use server side code on GitHub pages or static servers, you can't do this. The goal is to make it work just like the original works with the twitter API.

**Comment by mariobehling** [comment]
Please check out this development of another student. You can base your work on this and improve the look and ease of functioning. Demo: http://cagriari.com/tweetsearch Source: https://github.com/hesapadim/tweet-search-advance

**Comment by mariobehling** [comment]
Hm, I just see, that this is not implemented in Javascript. So, it does not work.

**Comment by anshuman73** [comment]
well, I'm working with https://github.com/YagoGG/loklak-fetcher-client
Made by another GCI student. He's allowed me to use it.
It has extensive features. I'm developing the front end for this right now. I think yago even talked to you about we collaborating together. That script might actually work
